version: "3.7"
services:
  database_finan:
    image: postgres
    container_name: DBContainerFinan
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=DBAppFinan
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: appFinanContainer
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
    pgdata:
        driver: local